# Generated by Django 3.2.6 on 2021-08-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='defaults/avatar.png', upload_to='avatars/'),
        ),
    ]
