# Generated by Django 3.2.6 on 2021-09-01 04:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20210831_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmcode',
            name='code',
            field=models.CharField(default='487498', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='confirmcode',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 1, 5, 3, 16, 552883, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='code',
            field=models.CharField(default='0OBQO9', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
