# Generated by Django 3.2.6 on 2021-10-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_booklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
