# Generated by Django 3.2.6 on 2021-10-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_booklist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, related_name='book_lists', to='core.Book'),
        ),
    ]
