# Generated by Django 3.2.6 on 2021-09-03 07:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210901_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_invited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='confirmcode',
            name='code',
            field=models.CharField(default='940808', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='confirmcode',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 3, 8, 4, 38, 993587, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='code',
            field=models.CharField(default='EWF8XZ', max_length=255, unique=True),
        ),
    ]
