# Generated by Django 3.2.6 on 2021-08-26 07:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210826_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmcode',
            name='code',
            field=models.CharField(default='465216', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='confirmcode',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 7, 48, 49, 706580, tzinfo=utc)),
        ),
    ]
