# Generated by Django 3.2.6 on 2022-01-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='raw_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
