# Generated by Django 3.2.6 on 2022-04-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_reportbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_posts/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
