# Generated by Django 3.2.6 on 2022-04-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_book_source_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='is_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publisher',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='publishers/'),
        ),
    ]
