# Generated by Django 3.2.6 on 2022-04-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20220429_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='books',
            field=models.ManyToManyField(related_name='book_lists', to='core.Book'),
        ),
    ]
