# Generated by Django 3.2.6 on 2022-04-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_booklist_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryposts',
            name='url',
        ),
        migrations.AddField(
            model_name='categoryposts',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='category_posts', to='core.Book'),
        ),
    ]
