# Generated by Django 3.2.6 on 2022-05-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_baners'),
    ]

    operations = [
        migrations.AddField(
            model_name='baners',
            name='slider',
            field=models.CharField(choices=[('slider1', 'slider1'), ('slider2', 'slider2')], default='slider1', max_length=150),
        ),
    ]
