"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'oops-i-did-it-again.'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

"""
    'https://nebig.iran.liara.run/',
    'https://api.nebigapp.com/',
    'localhost',
    '127.0.0.1',
"""

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    
    # API:
    'rest_framework',
    'rest_framework.authtoken',
    'dj_rest_auth',
    
    # Apps:
    'core.apps.CoreConfig',
    'user.apps.UserConfig',
    'book.apps.BookConfig',
    'booklist.apps.BooklistConfig',
    'info.apps.InfoConfig',
    'accounts.apps.AccountsConfig',
    'web.apps.WebConfig',
    'main.apps.MainConfig',
    'scrapers.apps.ScrapersConfig',

    # Third-parties:
    'drf_yasg',
    'corsheaders',
    'django_extensions',
    'crispy_forms',
    'allauth',
    'allauth.account',
    'allauth.socialaccount', 
    'allauth.socialaccount.providers.google', # For google auth
    
    # Custom Modules:
    'utils',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Cors Headers
"""
Access to XMLHttpRequest at 'https://api.nebigapp.com/user/me/' from origin 'https://pwa.nebigapp.ir' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
"""

CORS_ORIGIN_WHITELIST = [
    'https://nebig.iran.liara.run',
    'https://api.nebigapp.com',
    'localhost',
    'http://127.0.0.1:8000',
    'http://localhost:4200',
    'http://localhost:8000',
    'http://localhost:8080',
    'http://localhost:3000',
    'http://localhost:8081',
    'https://pwa.nebigapp.ir',
    'https://nebigapp.ir',
    'https://nebigapp.iran.liara.run',
    'https://api.nebigapp.ir',
]
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = (
    'GET',
    'POST',
    'PUT',
    'DELETE',
    'OPTIONS',
    'HEAD',
    'PATCH',
)

CORS_ALLOW_HEADERS = (
    'XMLHttpRequest',
    'Content-Type',
    'Authorization',
    'Origin',
    'Accept',
    'Accept-Encoding',
    'Accept-Language',
    'DNT',
    'Cache-Control',
    'Pragma',
    'User-Agent',
    'X-Requested-With',
    'If-Modified-Since',
    'If-None-Match',
    'Connection',
    'Upgrade-Insecure-Requests',
    'Sec-Fetch-User',
    'Sec-Fetch-Site',
    'Sec-Fetch-Mode',
    'Sec-Fetch-Dest',
    'Sec-Fetch-Tainting',
    'Accept-Ranges',
    'Range',
    'Referer',
    'Origin',
    'Access-Control-Request-Method',
    'Access-Control-Request-Headers',
    'Access-Control-Allow-Origin',
    'Access-Control-Allow-Credentials',
    'Access-Control-Allow-Methods',
    'Access-Control-Allow-Headers',
    'Access-Control-Expose-Headers',
    'Access-Control-Max-Age',
    
    # Flutter
    'X-Flutter-Version',
    'X-Flutter-Platform',
    'X-Flutter-Locale',
    'X-Flutter-Locale-Country',
    'X-Flutter-Locale-Language',
    'X-Flutter-Locale-Script',
    'X-Flutter-Locale-Variant',
    'X-Flutter-Locale-Extension',
    'X-Flutter-Locale-Short',
    'X-Flutter-Locale-Short-Extension',
    'X-Flutter-Locale-Short-Script',
    'X-Flutter-Locale-Short-Variant',
    'X-Flutter-Locale-Short-Country',
    'X-Flutter-Locale-Short-Language',
    'X-Flutter-Locale-Short-Region',
    )


AUTHENTICATION_BACKENDS = [
    # Used for default signin such as loggin into admin panel.
    'django.contrib.auth.backends.ModelBackend', 
    # Used for social authentications.
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
'''
DATABASES = {
    # PostgreSQL
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'apidb',
        'USER': 'root',
        'PASSWORD': 'PP2H0P1xEGSK9W33NT3ZfezB',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}
'''
DATABASES = {
    # SQLite
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}



# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

import os

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# Goole Settings Email
"""
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'mehrshadbaqerzadegan@gmail.com'
EMAIL_HOST_PASSWORD = 'hvraafhhdyqluxmz'
EMAIL_PORT = 587
""" 
# Nebig Settings Email
EMAIL_HOST = 'smtp.iran.liara.ir'
EMAIL_HOST_USER = 'nebig'
EMAIL_HOST_PASSWORD = '521ee760-055d-49d4-9f3a-4b5e9b856029'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

STATIC_URL = '/static/'

import os
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 2
}

BASE_URL = 'https://api.nebigapp.com'
